
name: "Telegram Menu Builder"
description: "Генератор Telegram-меню с кнопками для управления устройствами Home Assistant"
version: "1.0.3"
slug: "telegram_menu_builder"
startup: services
boot: auto
arch:
  - amd64
  - aarch64
  - armv7
hassio_api: true
homeassistant_api: true
options: {}
schema: {}
ports:
  8123/tcp: 9123
